config/routes.rb
Rails.application.routes.draw do
  
  root 'categories#index'
  resources :products
  resources :categories do collection {post :import} end
  
  get 'categories', to: 'categories#index'

  get 'start', to: 'pages#import'

end

app/models/category.rb
class Category < ActiveRecord::Base
  require 'csv'
  
  #1 category has many products
  has_many :products
  
  #category must be created with the category field entered.
  validates :category, presence: true
  
  #method to idempotently import products and categories from CSV stored in tmp folder
  def self.import
    CSV.foreach(Rails.root.join('tmp', 'products.csv'), headers: true) do |row|
      @product_IDs = Product.pluck('product_id')
      @categories = Category.pluck('category')
      
      #check if category exists, creates new category if not.
      if @categories.exclude? row[1]
        Category.create category: row[1]
      end
      
      #check if product exists, creates new product if not.
      if @product_IDs.exclude? row[0]
        category = Category.find_by category: row[1]
        Product.create name: row[2], price: row[3], category_id: category.id, product_id: row[0]
      end
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  #1 product has 1 category
  belongs_to :category
  
  #all product fields must be present to be create a product in the db
  validates :name, presence: true
  validates :price, presence: true
  validates :category_id, presence: true
  validates :product_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  #retrieves all stored categories from database for index view in alphabetical order
  def index
    @categories = Category.all.order("category")
  end

  #creates new category, saves it to the db (used when importing from CSV)
  def create
    @category = Category.new(category_params)
    @category.save
  end
  
  #retrieves all products in alphabetical order from a given category for the category show view in alphabetical order
  def show
    @category = Category.find(params[:id])
    @category_products = @category.products.paginate(page: params[:page], per_page:5).order("name")
  end

  #handles importing of CSV file - CSV is stored in tmp directory
  def import
    #throws error if importing csv file fails
    begin
      Category.import
      notice = "Import Complete"
    rescue
      notice = "There was an error whilst importing!"
    ensure
      redirect_to start_path, notice: notice
    end
  end
  
  private
    def category_params
      params.require(:category).permit(:category)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  #creates new product and saves it for use when importing from CSV
  def create
    @product = Product.new(product_params)
    @product.save
  end
  
  #retrieves product for products#show view
  def show
    @product = Product.find(params[:id])

    #retreives category for user to return to category page
    @category = Category.find_by id: @product.category_id
  end

  private
  def product_params
    params.require(:product).permit(:name, :price, :category_id, :product_id)
  end
end

  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<!--View for displaying all categories (this is the root path)-->
<h1 align="center">Select a Category:</h1>
<% @categories.each do |category|%>
  <div class='row'>
    <div class='col-xs-8 col-xs-offset-2'>
      <div class='well well-lg'>
        <div class='category-title'>
          <%= link_to category.category, category_path(category) %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/categories/show.html.erb
<!--View for displaying all products within a category-->
<h1 align="center"><%= @category.category %> Products:</h1>
<% @category_products.each do |product| %>
  <div class='row'>
    <div class='col-xs-8 col-xs-offset-2'>
      <div class='well well-lg'>
        <div class='category-title'>
          <%= link_to product.name, product_path(product) %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<div align="center">
  <%= will_paginate @category_products %>
</div>
<div align="center">
  [ <%= link_to 'Back to Categories', root_path %> ]
</div>

app/views/layouts/_navigation.html.erb
<!--Navbar for providing links to home page and import CSV page-->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "View Categories", root_path, class: "navbar-brand" %>
      <%= link_to "Import CSV", start_path, class: "navbar-brand" %>
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!--default application template-->
<!DOCTYPE html>
<html>
<head>
  <title>OnlineStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation' %>
<%= yield %>

</body>
</html>

app/views/pages/import.html.erb
<!--View for providing import CSV interface-->
<div class='row'>
  <div class='col-xs-8 col-xs-offset-2'>
    <div class='well well-lg'>
      <h3>Import Data from CSV:</h3>
        <%= form_tag import_categories_path, multipart: true do %>
          <%= submit_tag "Trigger Import" %>
        <% end %>
        <br>
        <%= flash[:notice] %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<!--View for displaying a particular products name and price-->
<div class='row'>
    <div class='col-xs-8 col-xs-offset-2'>
      <div class='well well-lg'>
        <div class='category-title'>
          <p>
            <%= @product.name %>
          </p>
          <p>
            <span class="label">Price:</span><span class="label-price"><%= number_to_currency(@product.price) %></span>
          </p>
        </div>
      </div>
    </div>
  </div>
<div align="center">
  [ <%= link_to 'Back to ' + @category.category , category_path(@category) %> ]
</div>